name: Check types
on: [pull_request]
env:
  NODE_VERSION: '16' # Shipped with VS Code.

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install python deps
        run: pip install -r requirement-setuptools.txt -r requirements.txt -r dev-requirements.txt -e.
      - name: Install node deps
        run: npm ci
      - name: Check types
        run: npx pyright
